name: 'Semver Increment'
description: 'Gets the previous semver tag and calculates the next version. Optionally apply the version as a new tag.'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
inputs:
  GITHUB_TOKEN:
    description: The github token.
    required: true
  base-version:
    description: 'The version which the latest subfield of will be incremented.'
    default: "*"
    required: false
  release-type:
    description: 'Which Semver element to increment?'
    required: false
    default: patch
  preid:
    description: 'The prerelease identifier to use.'
    default: "pre"
    required: false
  dry-run:
    description: 'Performs a version calculation without committing a tag.'
    required: false
    default: "false"

outputs:
  next-version:
    description: 'The calculated version number.'


runs:
  using: 'node16'
  main: 'dist/index.js'
